name: Guestbook

on:
  issues:
    types: [opened]

jobs:
  update-guestbook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    if: contains(github.event.issue.labels.*.name, 'guestbook')
    steps:
      - uses: actions/checkout@v3
      - name: Update Guestbook
        uses: kaustubhhiware/readme-guestbook@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          template: "  - **[@{{ name }}](https://github.com/{{ username }})**: {{ message }}  "
